// <auto-generated />
using System;
using Budget_Tracker_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budget_Tracker_WebAPI.Migrations
{
    [DbContext(typeof(Db15765Context))]
    partial class Db15765ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.BudgetMaster", b =>
                {
                    b.Property<Guid>("BudgetMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TransactionCategoryMasterId")
                        .HasColumnType("int(11)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserMasterId")
                        .HasColumnType("char(36)");

                    b.HasKey("BudgetMasterId");

                    b.HasIndex("TransactionCategoryMasterId");

                    b.HasIndex("UserMasterId");

                    b.ToTable("BudgetMaster");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.CurrencyMaster", b =>
                {
                    b.Property<int>("CurrencyMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CurrencyMasterId"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CurrencyMasterId");

                    b.ToTable("CurrencyMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionCategoryMaster", b =>
                {
                    b.Property<int>("TransactionCategoryMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_category_master_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionCategoryMasterId"));

                    b.Property<sbyte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("TransactionCategoryName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("transaction_category_name");

                    b.Property<int?>("TransactionTypeMasterId")
                        .HasColumnType("int(11)");

                    b.Property<Guid?>("UserMasterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_master_id");

                    b.HasKey("TransactionCategoryMasterId")
                        .HasName("PRIMARY");

                    b.HasIndex("TransactionTypeMasterId");

                    b.HasIndex(new[] { "UserMasterId" }, "user_master_id_idx");

                    b.ToTable("transaction_category_master", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionMaster", b =>
                {
                    b.Property<Guid>("TransactionMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("transaction_master_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<sbyte?>("IsActive")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("isActive");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("double")
                        .HasColumnName("transaction_amount");

                    b.Property<int>("TransactionCategoryMasterId")
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_category_master_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("transaction_description");

                    b.Property<string>("TransactionNote")
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_note");

                    b.Property<int?>("TransactionPaymentmodeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_paymentmodeId");

                    b.Property<int>("TransactionTypeMasterId")
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_type_master_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionMasterId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TransactionCategoryMasterId" }, "transaction_category_master_idx");

                    b.HasIndex(new[] { "TransactionPaymentmodeId" }, "transaction_paymernt_mode_idx");

                    b.HasIndex(new[] { "TransactionTypeMasterId" }, "transaction_type_master_idx");

                    b.HasIndex(new[] { "UserId" }, "user_master_idx");

                    b.ToTable("transaction_master", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionPaymentMode", b =>
                {
                    b.Property<int>("PaymentModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("paymentModeId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentModeId"));

                    b.Property<sbyte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("paymentMode");

                    b.Property<Guid?>("UserMasterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userMasterId");

                    b.HasKey("PaymentModeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserMasterId" }, "usermasterID_FK_idx");

                    b.ToTable("transaction_payment_mode", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionTypeMaster", b =>
                {
                    b.Property<int>("TransactionTypeMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_type_master_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionTypeMasterId"));

                    b.Property<sbyte?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("TransactionTypename")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("transaction_typename");

                    b.Property<Guid?>("UserMasterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_master_id");

                    b.HasKey("TransactionTypeMasterId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserMasterId" }, "user_master_id_idx")
                        .HasDatabaseName("user_master_id_idx1");

                    b.ToTable("transaction_type_master", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.UserMaster", b =>
                {
                    b.Property<Guid>("UserMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserMasterID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CurrencyMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)");

                    b.Property<sbyte?>("IsActive")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("LastName")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserRoleID");

                    b.HasKey("UserMasterId")
                        .HasName("PRIMARY");

                    b.HasIndex("CurrencyMasterId");

                    b.HasIndex(new[] { "UserRoleId" }, "RoleIdMaster_idx");

                    b.ToTable("user_master", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.UserRoleMaster", b =>
                {
                    b.Property<int>("UserRoleMasterId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserRoleMasterID");

                    b.Property<sbyte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("UserRole")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("UserRoleMasterId")
                        .HasName("PRIMARY");

                    b.ToTable("user_role_master", (string)null);
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.BudgetMaster", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.TransactionCategoryMaster", "TransactionCategoryMaster")
                        .WithMany("BudgetMasters")
                        .HasForeignKey("TransactionCategoryMasterId");

                    b.HasOne("Budget_Tracker_WebAPI.Models.UserMaster", "UserMaster")
                        .WithMany("BudgetMasters")
                        .HasForeignKey("UserMasterId");

                    b.Navigation("TransactionCategoryMaster");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionCategoryMaster", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.TransactionTypeMaster", "TransactionTypeMaster")
                        .WithMany("TransactionCategoryMasters")
                        .HasForeignKey("TransactionTypeMasterId");

                    b.HasOne("Budget_Tracker_WebAPI.Models.UserMaster", "UserMaster")
                        .WithMany("TransactionCategoryMasters")
                        .HasForeignKey("UserMasterId")
                        .HasConstraintName("user_master_id");

                    b.Navigation("TransactionTypeMaster");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionMaster", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.TransactionCategoryMaster", "TransactionCategoryMaster")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("TransactionCategoryMasterId")
                        .IsRequired()
                        .HasConstraintName("transaction_category_master");

                    b.HasOne("Budget_Tracker_WebAPI.Models.TransactionPaymentMode", "TransactionPaymentmode")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("TransactionPaymentmodeId")
                        .HasConstraintName("transaction_paymernt_mode");

                    b.HasOne("Budget_Tracker_WebAPI.Models.TransactionTypeMaster", "TransactionTypeMaster")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("TransactionTypeMasterId")
                        .IsRequired()
                        .HasConstraintName("transaction_type_master");

                    b.HasOne("Budget_Tracker_WebAPI.Models.UserMaster", "User")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_master");

                    b.Navigation("TransactionCategoryMaster");

                    b.Navigation("TransactionPaymentmode");

                    b.Navigation("TransactionTypeMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionPaymentMode", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.UserMaster", "UserMaster")
                        .WithMany("TransactionPaymentModes")
                        .HasForeignKey("UserMasterId")
                        .HasConstraintName("usermasterID_FK");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionTypeMaster", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.UserMaster", "UserMaster")
                        .WithMany("TransactionTypeMasters")
                        .HasForeignKey("UserMasterId")
                        .HasConstraintName("user_master_id_fk");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.UserMaster", b =>
                {
                    b.HasOne("Budget_Tracker_WebAPI.Models.CurrencyMaster", "CurrencyMaster")
                        .WithMany("UserMasters")
                        .HasForeignKey("CurrencyMasterId");

                    b.HasOne("Budget_Tracker_WebAPI.Models.UserRoleMaster", "UserRole")
                        .WithMany("UserMasters")
                        .HasForeignKey("UserRoleId")
                        .HasConstraintName("RoleIdMaster");

                    b.Navigation("CurrencyMaster");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.CurrencyMaster", b =>
                {
                    b.Navigation("UserMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionCategoryMaster", b =>
                {
                    b.Navigation("BudgetMasters");

                    b.Navigation("TransactionMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionPaymentMode", b =>
                {
                    b.Navigation("TransactionMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.TransactionTypeMaster", b =>
                {
                    b.Navigation("TransactionCategoryMasters");

                    b.Navigation("TransactionMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.UserMaster", b =>
                {
                    b.Navigation("BudgetMasters");

                    b.Navigation("TransactionCategoryMasters");

                    b.Navigation("TransactionMasters");

                    b.Navigation("TransactionPaymentModes");

                    b.Navigation("TransactionTypeMasters");
                });

            modelBuilder.Entity("Budget_Tracker_WebAPI.Models.UserRoleMaster", b =>
                {
                    b.Navigation("UserMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
